---
title: "Calculate biodiversity indicator uncertainty"
subtitle: "Bootstrapping
author: "Ward Langeraert"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(b3gbi)
library(tidyverse)
```

# Exploration of the b3gbi package

We install b3gbi package version 0.2.1.
We load a dataset from the package.
How does the cube look like?

```{r}
# Load GBIF data cube
cube_name <- system.file("extdata", "europe_insect_cube.csv", package = "b3gbi")

# Load taxonomic info for cube
tax_info <- system.file("extdata", "europe_insect_info.csv", package = "b3gbi")

insect_data_df <- read.csv(cube_name)
head(insect_data_df)
```

We process the cube.

```{r}
# Prepare cube
insect_data <- process_cube_old(cube_name, tax_info)

insect_data
```

> Where did the info on min. coordinate uncertainty in meters go?

```{r}
# Calculate diversity metric
map_obs_rich_insects <- obs_richness_map(insect_data)

print(map_obs_rich_insects)
```

```{r}
# Plot diversity metric
plot(map_obs_rich_insects,
     title = "Observed Species Richness: Insects in Europe")
```

