---
title: "Compare bootstrapping software"
author: "Ward Langeraert"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: show
    toc: true
    toc_float: true
    toc_collapsed: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE, message=FALSE}
# Load packages
library(b3gbi)       # Biodiversity indicators for data cubes
library(tidyverse)   # Data wrangling and visualisation
library(here)        # Relative paths

# Source functions
source(here("source", "R", "perform_bootstrap_ts.R"))
source(here("source", "R", "bootstrap_list_to_df.R"))
source(here("source", "R", "get_bootstrap_ci_old.R"))
source(here("source", "R", "bootstrap_cube.R"))
source(here("source", "R", "get_bootstrap_ci.R"))
```

# Introduction

We want to compare the **boot** package output with our own functions.

# Data

We use the Mammal data of Denmark from **b3gbi**.

```{r}
cube_file <- system.file("extdata", "denmark_mammals_cube_eqdgc.csv",
                         package = "b3gbi")
denmark_cube <- process_cube(cube_file, first_year = 2005, last_year = 2013)
denmark_cube
```

```{r}
plot(obs_richness_ts(denmark_cube))
```

```{r}
plot(obs_richness_map(denmark_cube))
```

# Bootstrapping
## boot package

Define bootstrap functions and perform bootstrapping.

```{r}
# Define function for calculating statistic
mean_obs <- function(data) {
  mean(data$obs)
}

# Define bootstrapping for a calculated statistic
boot_statistic <- function(data, indices, fun) {
  d <- data[indices, ]
  return(fun(d))
}
```

```{r}
# Bootstrapping
set.seed(123)
boot_samples <- 1000

# Group by year
bootstrap_list_denmark <- denmark_cube$data %>%
  split(denmark_cube$data$year) %>%
  # Perform bootstrapping
  lapply(function(x) {
    boot::boot(
      data = x,
      statistic = boot_statistic,
      R = boot_samples,
      fun = mean_obs)
  })

# Summarise in dataframe
bootstrap_denmark_full <- bootstrap_list_to_df(bootstrap_list_denmark)
bootstrap_denmark_full
```

Calculate confidence intervals.

```{r, warning=FALSE}
# Calculate confidence intervals
ci_denmark <- get_bootstrap_ci_old(
  bootstrap_list_denmark,
  fun = mean_obs,
  type = c("perc", "norm", "basic"))

# Join dataframes
bootstrap_denmark_final <- bootstrap_denmark_full %>%
  full_join(ci_denmark, by = join_by(year), relationship = "many-to-many")

bootstrap_denmark_final
```

Visualise results.

```{r}
estimate_df <- bootstrap_denmark_final %>%
  distinct(year, estimate = est_original, bias_boot)

bootstrap_denmark_final %>%
  ggplot(aes(x = year)) +
    geom_violin(aes(y = est_boot, group = year),
                fill = alpha("cornflowerblue", 0.2)) +
    geom_errorbar(aes(ymin = ll, ymax = ul, colour = int_type),
                  position = position_dodge(0.8), linewidth = 1) +
    geom_point(data = estimate_df, aes(y = estimate),
               colour = "firebrick", size = 2) +
    labs(y = "Mean number of observations", colour = "Confidence interval") +
    scale_y_continuous(limits = c(0, NA), breaks = seq(0, 50, 5)) +
    scale_x_continuous(breaks = sort(unique(bootstrap_denmark_final$year))) +
    theme_minimal() +
    theme(legend.position = "bottom")
```

## Custom functions

Perform the same analysis with own functions.

```{r}
# Define function for calculating statistic
mean_obs2 <- function(data) {
  aggregate(data$obs,
            by = list(year = data$year),
            FUN = mean) %>%
    rename("diversity_val" = "x")
}

# Bootstrapping
bootstrap_denmark2 <- bootstrap_cube(
  data_cube = denmark_cube$data,
  fun = mean_obs2,
  grouping_var = "year",
  samples = 1000,
  seed = 123)

# Calculate confidence intervals
ci_denmark2 <- get_bootstrap_ci(
  bootstrap_samples_df = bootstrap_denmark2,
  grouping_var = "year",
  type = c("perc", "norm", "basic"),
  conf = 0.95,
  aggregate = FALSE)
```

The results compare very well.

```{r}
years <- sort(unique(bootstrap_denmark_final$year))
year_list <- split(years, ceiling(seq_along(years) / 3))

for (i in seq_along(year_list)) {
  year_group <- year_list[[i]]

  p <- bind_rows(
      bootstrap_denmark_final %>%
        mutate(package = "boot",
               int_type = ifelse(int_type == "normal", "norm", int_type),
               int_type = ifelse(int_type == "percent", "perc", int_type)) %>%
        rename("rep_boot" = "est_boot"),
      ci_denmark2 %>%
        mutate(package = "dubicube")
    ) %>%
    filter(year %in% year_group) %>%
    ggplot(aes(x = package)) +
      geom_violin(aes(y = rep_boot, group = package),
                  fill = alpha("cornflowerblue", 0.2)) +
      geom_errorbar(aes(ymin = ll, ymax = ul, colour = int_type),
                    position = position_dodge(0.8), linewidth = 1,
                    width = 0.5) +
      labs(y = "Mean number of observations", colour = "Confidence interval") +
      scale_y_continuous(limits = c(0, NA), breaks = seq(0, 50, 5)) +
      facet_grid(int_type ~ year) +
      theme_minimal() +
      theme(legend.position = "bottom")
  print(p)
}
```

```{r}
bind_rows(
    bootstrap_denmark_final %>%
      mutate(package = "boot",
             int_type = ifelse(int_type == "normal", "norm", int_type),
             int_type = ifelse(int_type == "percent", "perc", int_type)) %>%
      rename("rep_boot" = "est_boot"),
    ci_denmark2 %>%
      mutate(package = "dubicube")
  ) %>%
  distinct(year, package, int_type, ll, ul) %>%
  arrange(year, int_type, package) %>%
  knitr::kable(digits = 5)
```
