---
title: "Calculate biodiversity indicator uncertainty via bootstrapping on the complete cube"
author: "Ward Langeraert"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: show
    toc: true
    toc_float: true
    toc_collapsed: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE, message=FALSE}
# Load packages
library(b3gbi)       # Biodiversity indicators for data cubes
library(tidyverse)   # Data wrangling and visualisation
library(ggrepel)     # Repel labels in ggplot
library(here)        # Relative paths
library(effectclass) # Classification and visualisation of effects
library(knitr)       # Nice tables

# Source functions
source(here("source", "R", "evenness_formula.R"))
source(here("source", "R", "perform_bootstrap_ts.R"))
source(here("source", "R", "bootstrap_list_to_df.R"))
source(here("source", "R", "get_bootstrap_ci_old.R"))
source(here("source", "R", "add_classification_as_factor.R"))
source(here("source", "R", "leave_one_species_out_ts.R"))
source(here("source", "R", "utils.R"))
```

# Introduction

# Data

```{r}
cube_file <- system.file("extdata", "denmark_mammals_cube_eqdgc.csv",
                         package = "b3gbi")
denmark_cube <- process_cube(cube_file, first_year = 2005, last_year = 2013)
denmark_cube
```

```{r}
plot(obs_richness_ts(denmark_cube))
```

```{r}
plot(obs_richness_map(denmark_cube))
```

# Bootstrapping

```{r}
# Define function for calculating statistic
mean_obs <- function(data) {
  mean(data$obs)
}

# Define bootstrapping for a calculated statistic
boot_statistic <- function(data, indices, fun) {
  d <- data[indices, ]
  return(fun(d))
}
```

```{r}
# Bootstrapping
set.seed(123)
boot_samples <- 1000

# Group by year
bootstrap_list_denmark <- denmark_cube$data %>%
  split(denmark_cube$data$year) %>%
  # Perform bootstrapping
  lapply(function(x) {
    boot::boot(
      data = x,
      statistic = boot_statistic,
      R = boot_samples,
      fun = mean_obs)
  })

# Summarise in dataframe
bootstrap_denmark_full <- bootstrap_list_to_df(bootstrap_list_denmark)
bootstrap_denmark_full
```


```{r, warning=FALSE}
# Calculate confidence intervals
ci_denmark <- get_bootstrap_ci_old(bootstrap_list_denmark, fun = mean_obs)

# Join dataframes
bootstrap_denmark_final <- bootstrap_denmark_full %>%
  full_join(ci_denmark, by = join_by(year), relationship = "many-to-many")

bootstrap_denmark_final
```

```{r}
numbers_data <- denmark_cube$data %>%
  group_by(year) %>%
  summarize(n = n(),
            n_spec = n_distinct(taxonKey),
            .groups = "drop") %>%
  mutate(label_n = paste("n", n, sep = "="),
         label_spec = paste("n_spec", n_spec, sep = "="),
         label_tot = paste(label_n, label_spec, sep = "\n"))

estimate_df <- bootstrap_denmark_final %>%
  distinct(year, estimate = est_original, bias_boot)

bootstrap_denmark_final %>%
  ggplot(aes(x = year)) +
    geom_violin(aes(y = est_boot, group = year), fill = alpha("cornflowerblue", 0.2)) +
    geom_errorbar(aes(ymin = ll, ymax = ul, colour = int_type),
                  position = position_dodge(0.8), linewidth = 1) +
    geom_point(data = estimate_df, aes(y = estimate),
               colour = "firebrick", size = 3) +
    labs(y = "Mean number of observations", colour = "Confidence interval") +
    scale_y_continuous(limits = c(0, NA), breaks = seq(0, 50, 5)) +
    scale_x_continuous(breaks = sort(unique(bootstrap_denmark_final$year))) +
    theme_minimal() +
    theme(legend.position = "bottom")
```

