---
title: "Visualisation of spatial uncertainty"
author: "Ward Langeraert"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
    toc_collapsed: true
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../output/reports") })
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE, message=FALSE}
# Load packages
library(ggplot2) # visualisation
library(sf)      # spatial objects
library(dplyr)   # data wrangling
library(ggblur)  # blurred points: https://github.com/coolbutuseless/ggblur

# Out path
out_path <- here::here("output", "figures", "visualise_spatial_uncertainty")
dir.create(out_path, showWarnings = FALSE, recursive = TRUE)
```

# Goal

Investigate visualisation of spatial uncertainty.

https://doi.org/10.1559/1523040054738936

https://doi.org/10.1179/1743277414Y.0000000099

```{r, warning=FALSE}
# Create a simple 3x3 grid using sf
grid_size <- 1  # Define cell size
grid <- expand.grid(x = 1:3, y = 1:3) %>%
  st_as_sf(coords = c("x", "y"), crs = 4326) %>%
  st_make_grid(cellsize = grid_size, n = c(3, 3), what = "polygons") %>%
  st_sf() %>%
  mutate(id = seq_len(n()))

centroids <- st_centroid(grid) %>%
  st_buffer(50000)

# Create data for estimates and uncertainty
data <- expand.grid(
  x = 1:3 + 0.5,  # Columns for estimate values
  y = 1:3 + 0.5   # Rows for uncertainty levels
) %>%
  mutate(
    # Low, Medium, High estimates
    estimate = rep(c(0.2, 0.5, 0.8), each = 3),
    # Low, Medium, High uncertainty
    uncertainty = rep(c("Low", "Medium", "High"), times = 3)
  )

# Assign visual properties for uncertainty representation
data <- data %>%
  mutate(
    blur_size = case_when(uncertainty == "Low" ~ NA,
                          uncertainty == "Medium" ~ 25,
                          uncertainty == "High" ~ 30),
    blur_size2 = case_when(uncertainty == "Low" ~ NA,
                      uncertainty == "Medium" ~ 15,
                      uncertainty == "High" ~ 30),
    alpha_value = case_when(uncertainty == "Low" ~ 1,
                            uncertainty == "Medium" ~ 0.6,
                            uncertainty == "High" ~ 0.3),
    size = case_when(uncertainty == "Low" ~ 30,
                     uncertainty == "Medium" ~ 15,
                     uncertainty == "High" ~ 10),
  )

# Convert data to sf points for plotting
data_sf <- cbind(centroids, data)
```

# Blur

Increasing blur with increasing uncertainty:

```{r}
p_blur <- ggplot() +
  geom_sf(data = grid, color = "black", alpha = 0,
          linewidth = 1) +  # Grid background
  geom_point_blur(
    data = data_sf %>% filter(uncertainty == "High"),
    aes(x = x, y = y, colour = estimate, blur_size = blur_size),
    size = 1) +
  geom_point_blur(
    data = data_sf %>% filter(uncertainty == "Medium"),
    aes(x = x, y = y, colour = estimate, blur_size = blur_size),
    size = 15) +
  geom_point(
    data = data_sf %>% filter(uncertainty == "Low"),
    aes(x = x, y = y, colour = estimate),
    size = 30) +
  scale_colour_viridis_c(option = "D") +
  scale_blur_size_continuous(range = c(20, 35)) +
  theme_minimal() +
  theme(panel.grid = element_line(linewidth = 1),
        legend.title = element_text(face = "bold")) +
  labs(title = "Blur", x = "", y = "", colour = "Estimate:") +
  guides(blur_size = "none") +
  annotate("segment",
    x = 1.5,
    y = 0.8,
    xend = 3.5,
    yend = 0.8,
    linewidth = 1,
    arrow = arrow(type = "closed", length = unit(0.02, "npc")),
    colour = "black"
  ) +
  annotate("segment",
    x = 0.8,
    y = 1.5,
    xend = 0.8,
    yend = 3.5,
    linewidth = 1,
    arrow = arrow(type = "closed", length = unit(0.02, "npc")),
    colour = "black"
  ) +
  annotate("text",
    label = c("Higher uncertainty"),
    x = 2.5,
    y = 0.7,
    size = 5, hjust = "center", vjust = "center", colour = "black"
  ) +
  annotate("text",
    label = c("Higher estimate"),
    x = 0.7,
    y = 2.5,
    size = 5, hjust = "center", vjust = "bottom", colour = "black", angle = 90
  )
p_blur
```

```{r}
p_blur2 <- ggplot() +
  geom_sf(data = grid, color = "black", alpha = 0,
          linewidth = 1) +  # Grid background
  geom_point_blur(
    data = data_sf %>% filter(uncertainty == "High"),
    aes(x = x, y = y, colour = estimate, blur_size = blur_size2),
    size = 1) +
  geom_point_blur(
    data = data_sf %>% filter(uncertainty == "Medium"),
    aes(x = x, y = y, colour = estimate, blur_size = blur_size2),
    size = 10) +
  geom_point(
    data = data_sf %>% filter(uncertainty == "Low"),
    aes(x = x, y = y, colour = estimate),
    size = 30) +
  scale_colour_viridis_c(option = "D") +
  scale_blur_size_continuous(range = c(15, 15)) +
  theme_minimal() +
  theme(panel.grid = element_line(linewidth = 1),
        legend.title = element_text(face = "bold")) +
  labs(title = "Blur + Size", x = "", y = "", colour = "Estimate:") +
  guides(blur_size = "none") +
  annotate("segment",
    x = 1.5,
    y = 0.8,
    xend = 3.5,
    yend = 0.8,
    linewidth = 1,
    arrow = arrow(type = "closed", length = unit(0.02, "npc")),
    colour = "black"
  ) +
  annotate("segment",
    x = 0.8,
    y = 1.5,
    xend = 0.8,
    yend = 3.5,
    linewidth = 1,
    arrow = arrow(type = "closed", length = unit(0.02, "npc")),
    colour = "black"
  ) +
  annotate("text",
    label = c("Higher uncertainty"),
    x = 2.5,
    y = 0.7,
    size = 5, hjust = "center", vjust = "center", colour = "black"
  ) +
  annotate("text",
    label = c("Higher estimate"),
    x = 0.7,
    y = 2.5,
    size = 5, hjust = "center", vjust = "bottom", colour = "black", angle = 90
  )
p_blur2
```

# Transparency

Increasing transparency with increasing uncertainty.

With `geom_sf()`.

```{r}
p_transparency <- ggplot() +
  geom_sf(data = grid, color = "black", alpha = 0,
          linewidth = 1) +  # Grid background
  geom_sf(data = data_sf, aes(fill = estimate, alpha = alpha_value),
          colour = alpha("white", 1)) +
  scale_fill_viridis_c(option = "D") +
  scale_alpha_identity() +
  theme_minimal() +
  theme(panel.grid = element_line(linewidth = 1),
        legend.title = element_text(face = "bold")) +
  labs(title = "Transparency", x = "", y = "", fill = "Estimate:") +
  annotate("segment",
    x = 1.5,
    y = 0.8,
    xend = 3.5,
    yend = 0.8,
    linewidth = 1,
    arrow = arrow(type = "closed", length = unit(0.02, "npc")),
    colour = "black"
  ) +
  annotate("segment",
    x = 0.8,
    y = 1.5,
    xend = 0.8,
    yend = 3.5,
    linewidth = 1,
    arrow = arrow(type = "closed", length = unit(0.02, "npc")),
    colour = "black"
  ) +
  annotate("text",
    label = c("Higher uncertainty"),
    x = 2.5,
    y = 0.7,
    size = 5, hjust = "center", vjust = "center", colour = "black"
  ) +
  annotate("text",
    label = c("Higher estimate"),
    x = 0.7,
    y = 2.5,
    size = 5, hjust = "center", vjust = "bottom", colour = "black", angle = 90
  )
p_transparency
```

With `geom_point()`.

```{r}
p_transparency2 <- ggplot() +
  geom_sf(data = grid, color = "black", alpha = 0,
          linewidth = 1) +  # Grid background
  geom_point(data = data_sf,
             aes(x = x, y = y, colour = estimate, alpha = alpha_value),
             size = 30) +
  scale_colour_viridis_c(option = "D") +
  scale_alpha_identity() +
  theme_minimal() +
  theme(panel.grid = element_line(linewidth = 1),
        legend.title = element_text(face = "bold")) +
  labs(title = "Transparency", x = "", y = "", colour = "Estimate:") +
  annotate("segment",
    x = 1.5,
    y = 0.8,
    xend = 3.5,
    yend = 0.8,
    linewidth = 1,
    arrow = arrow(type = "closed", length = unit(0.02, "npc")),
    colour = "black"
  ) +
  annotate("segment",
    x = 0.8,
    y = 1.5,
    xend = 0.8,
    yend = 3.5,
    linewidth = 1,
    arrow = arrow(type = "closed", length = unit(0.02, "npc")),
    colour = "black"
  ) +
  annotate("text",
    label = c("Higher uncertainty"),
    x = 2.5,
    y = 0.7,
    size = 5, hjust = "center", vjust = "center", colour = "black"
  ) +
  annotate("text",
    label = c("Higher estimate"),
    x = 0.7,
    y = 2.5,
    size = 5, hjust = "center", vjust = "bottom", colour = "black", angle = 90
  )
p_transparency2
```

With variable size:

```{r}
p_transparency3 <- ggplot() +
  geom_sf(data = grid, color = "black", alpha = 0,
          linewidth = 1) +  # Grid background
  geom_point(data = data_sf,
             aes(x = x, y = y, colour = estimate, alpha = alpha_value,
                 size = size)) +
  scale_colour_viridis_c(option = "D") +
  scale_alpha_identity() +
  scale_size_continuous(range = c(10, 30)) +
  theme_minimal() +
  theme(panel.grid = element_line(linewidth = 1),
        legend.title = element_text(face = "bold")) +
  labs(title = "Transparency + Size", x = "", y = "", colour = "Estimate:") +
  guides(size = "none") +
  annotate("segment",
    x = 1.5,
    y = 0.8,
    xend = 3.5,
    yend = 0.8,
    linewidth = 1,
    arrow = arrow(type = "closed", length = unit(0.02, "npc")),
    colour = "black"
  ) +
  annotate("segment",
    x = 0.8,
    y = 1.5,
    xend = 0.8,
    yend = 3.5,
    linewidth = 1,
    arrow = arrow(type = "closed", length = unit(0.02, "npc")),
    colour = "black"
  ) +
  annotate("text",
    label = c("Higher uncertainty"),
    x = 2.5,
    y = 0.7,
    size = 5, hjust = "center", vjust = "center", colour = "black"
  ) +
  annotate("text",
    label = c("Higher estimate"),
    x = 0.7,
    y = 2.5,
    size = 5, hjust = "center", vjust = "bottom", colour = "black", angle = 90
  )
p_transparency3
```

# Save figures

```{r}
ggsave(
  filename = file.path(out_path, "spat_uncertainty_blur.png"),
  plot = p_blur,
  dpi = 300,
  width = 6,
  height = 5)

ggsave(
  filename = file.path(out_path, "spat_uncertainty_blursize.png"),
  plot = p_blur2,
  dpi = 300,
  width = 6,
  height = 5)

ggsave(
  filename = file.path(out_path, "spat_uncertainty_trans.png"),
  plot = p_transparency2,
  dpi = 300,
  width = 6,
  height = 5)

ggsave(
  filename = file.path(out_path, "spat_uncertainty_transsize.png"),
  plot = p_transparency3,
  dpi = 300,
  width = 6,
  height = 5)
```

